const { Langfuse } = require('langfuse');
const { GoogleGenAI } = require('@google/genai');
const yargs = require('yargs/yargs');
const { hideBin } = require('yargs/helpers');
const fs = require('fs');
const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '../../.env') });

const argv = yargs(hideBin(process.argv))
  .option('skill', {
    alias: 's',
    type: 'string',
    description: 'The name of the skill executed',
    demandOption: true
  })
  .option('output', {
    alias: 'o',
    type: 'string',
    description: 'The path to the output file generated by the skill',
    demandOption: true
  })
  .option('input', {
    alias: 'i',
    type: 'string',
    description: 'The user request or input that triggered the workflow',
    demandOption: false
  })
  .help()
  .argv;

async function evaluateOutput(skillName, content) {
  if (!process.env.GOOGLE_API_KEY) {
    console.warn("⚠️ [Evaluator] GOOGLE_API_KEY is not set. Skipping evaluation.");
    return null;
  }
  
  try {
    const ai = new GoogleGenAI({ apiKey: process.env.GOOGLE_API_KEY });
    
    const prompt = `You are an expert AI evaluator. An AI agent has just executed the skill: "${skillName}".
Here is the output the agent generated:
---
${content}
---

Your task is to evaluate whether this output meets the general professional standards and expectations for the "${skillName}" phase of software development.
Score the output from 0.0 to 1.0 (where 1.0 is perfect compliance and quality, and 0.0 is completely wrong or missing).

Respond ONLY with a valid JSON object in this exact format, with no markdown formatting:
{
  "score": 0.85,
  "reason": "Brief explanation of the score"
}`;

    console.log("⏳ [Evaluator] Requesting evaluation from Google AI (Gemini)...");
    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash',
        contents: prompt,
        config: {
            temperature: 0.2,
            responseMimeType: "application/json"
        }
    });
    
    const resultText = response.text;
    const jsonResult = JSON.parse(resultText);
    console.log(`🧠 [Evaluator] Score: ${jsonResult.score} - ${jsonResult.reason}`);
    
    return jsonResult;
  } catch (error) {
    console.error("❌ [Evaluator] Failed to evaluate using Google AI:", error.message);
    return null;
  }
}

async function main() {
  if (!process.env.LANGFUSE_PUBLIC_KEY || !process.env.LANGFUSE_SECRET_KEY) {
    console.warn("⚠️ [Langfuse Tracker] LANGFUSE_PUBLIC_KEY or LANGFUSE_SECRET_KEY is not set. Please configure your .env file. Skipping trace.");
    return;
  }

  const langfuse = new Langfuse({
    publicKey: process.env.LANGFUSE_PUBLIC_KEY,
    secretKey: process.env.LANGFUSE_SECRET_KEY,
    baseUrl: process.env.LANGFUSE_BASE_URL || "http://localhost:3000"
  });

  const skillName = argv.skill;
  const outputPath = argv.output;
  const inputContent = argv.input || "No explicit input provided";

  let outputContent = "";
  try {
    const fullPath = path.resolve(process.cwd(), outputPath);
    outputContent = fs.readFileSync(fullPath, 'utf8');
  } catch (error) {
    console.error(`❌ [Langfuse Tracker] Failed to read output file at ${outputPath}:`, error.message);
    outputContent = "ERROR: Failed to read output file.";
  }

  console.log(`🚀 [Langfuse Tracker] Recording execution for skill: ${skillName}`);

  try {
    // 1. Create a trace (representing the whole workflow)
    const trace = langfuse.trace({
      name: "agent-workflow",
      input: inputContent,
      output: outputContent,
      tags: [skillName],
      metadata: {
        output_file: outputPath
      }
    });

    // 2. Create a span to represent the Workflow Routing decision
    trace.span({
      name: "skill-routing",
      input: inputContent,
      output: { selected_skill: skillName },
      startTime: new Date(Date.now() - 500), // Slightly offset for timeline ordering
      endTime: new Date()
    });

    // 3. Create a generation/span to log the skill result
    trace.generation({
      name: skillName,
      model: "copilot-agent",
      input: inputContent,
      completion: outputContent,
      endTime: new Date(),
    });

    // 3. Evaluate the output using Google AI
    const evaluation = await evaluateOutput(skillName, outputContent);

    // 4. Send the score to Langfuse if evaluation succeeded
    if (evaluation && typeof evaluation.score === 'number') {
      langfuse.score({
        traceId: trace.id,
        name: "rules_compliance",
        value: evaluation.score,
        comment: evaluation.reason
      });
      console.log(`✅ [Langfuse Tracker] Evaluator score attached to trace!`);
    }

    // Await flush to ensure events are sent
    await langfuse.flushAsync();
    console.log(`✅ [Langfuse Tracker] Successfully sent trace and evaluation to Langfuse.`);
    
  } catch (err) {
    console.error("❌ [Langfuse Tracker] Error sending trace to Langfuse:", err);
  }
}

main();
